export const digitalDemandCategories=[
 {id:'healthy-recipes',name:'Receitas e alimentação',keywords:['receitas saudáveis','marmita saudável','alimentação prática','receitas fitness'],product:'E-book de receitas práticas',risk:'health'},
 {id:'study',name:'Estudos e concursos',keywords:['como estudar','cronograma de estudos','concurso','revisão'],product:'Guia/Planner de estudos',risk:'standard'},
 {id:'finance-basics',name:'Organização financeira',keywords:['organizar orçamento','planilha gastos','economizar dinheiro'],product:'Planilha + guia de organização financeira',risk:'standard'},
 {id:'fitness-routine',name:'Rotina de exercícios',keywords:['treino iniciante','rotina academia','exercícios em casa'],product:'Planner de rotina de exercícios',risk:'health'},
 {id:'english',name:'Inglês',keywords:['aprender inglês','inglês iniciante','vocabulário inglês'],product:'Guia de estudo de inglês',risk:'standard'},
 {id:'pets',name:'Pets',keywords:['adestrar cachorro','rotina pet','cuidados cachorro'],product:'Guia de rotina e cuidados para pets',risk:'standard'}
];
function norm(v=''){return String(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
export function analyzePublicDemand(items=[]){return items.map(item=>{const text=norm([item.title,item.text,item.query,item.description].filter(Boolean).join(' '));let best=null;for(const c of digitalDemandCategories){const hits=c.keywords.filter(k=>text.includes(norm(k)));if(hits.length&&(!best||hits.length>best.hits.length))best={category:c,hits}}if(!best)return null;return {id:item.id||crypto.randomUUID(),source:item.source||'public',sourceUrl:item.sourceUrl||item.url||null,signalType:item.signalType||'public_or_aggregate',publishedAt:item.publishedAt||null,capturedAt:item.capturedAt||null,sourceQuality:Number(item.sourceQuality??.5),hasPublicContact:Boolean(item.hasPublicContact),evidence:item.evidence||item.text||'',categoryId:best.category.id,category:best.category.name,matchedTerms:best.hits,productSuggestion:best.category.product,risk:best.category.risk,score:Math.min(100,55+best.hits.length*15),contactPolicy:'Use apenas contato disponibilizado publicamente para finalidade comercial ou canal com opt-in. Não inferir condição de saúde nem identificar usuários de buscas privadas.',raw:{title:item.title||'',text:item.text||'',query:item.query||'',publishedAt:item.publishedAt||null,sourceQuality:Number(item.sourceQuality??.5)}}}).filter(Boolean)}
export function productBrief(signal){const health=signal.risk==='health';return {title:signal.productSuggestion,audience:`Pessoas interessadas publicamente em ${signal.category.toLowerCase()}`,positioning:health?'Conteúdo educacional geral, sem promessa de emagrecimento, ganho de peso, cura ou resultado médico.':'Conteúdo educacional e prático.',sections:health?['Introdução e limites do material','Organização de rotina','Ideias gerais e exemplos','Checklist prático','Quando buscar profissional qualificado']:['Introdução','Passo a passo','Exemplos','Checklist','Próximos passos'],cta:'Ver material',requiresReview:true}}
