function text(x={}){return `${x.category||''} ${x.title||''} ${x.problem||''} ${x.evidence||''} ${x.productSuggestion||''}`}
function productConcept(x={}){const t=text(x);if(x.risk==='health'||/emagrec|engord|peso|dieta|saúde|saude|fitness/i.test(t))return {format:'Guia digital educacional',title:`Guia prático: ${x.category||'hábitos e bem-estar'}`,angle:'Conteúdo informativo e organizacional, sem diagnóstico, prescrição ou promessa de resultado.',priceBand:'baixo ticket',requiresReview:true};if(/estudo|concurso|prova|enem|vestibular/i.test(t))return {format:'Ebook + checklist',title:`Plano prático de ${x.category||'estudos'}`,angle:'Passo a passo, rotina, revisão e material de acompanhamento.',priceBand:'baixo ticket',requiresReview:true};if(/finan|gasto|orçamento|planilha|dinheiro/i.test(t))return {format:'Planilha + guia',title:`Kit de organização: ${x.category||'finanças pessoais'}`,angle:'Organização e acompanhamento, sem promessa de ganho financeiro.',priceBand:'baixo ticket',requiresReview:true};if(/whatsapp|atendimento|chatbot|site|lead|agendamento|instagram/i.test(t))return {format:'Serviço/automação',title:`Solução de ${x.category||'automação comercial'}`,angle:'Demonstração focada no problema observado e proposta personalizada.',priceBand:'sob proposta',requiresReview:true};return {format:'Ebook ou mini-guia',title:`Guia prático: ${x.category||x.title||'solução digital'}`,angle:'Resolver uma dor específica com passos acionáveis e escopo simples.',priceBand:'baixo ticket',requiresReview:true}}
const actionRules=[
 {test:x=>x.risk==='health'||/emagrec|engord|peso|dieta|saúde|saude/i.test(text(x)),actions:['Definir guia educacional sem promessa de resultado','Criar conteúdo revisável e referências','Preparar landing page com linguagem responsável','Validar oferta antes de publicar']},
 {test:x=>/estudo|concurso|prova/i.test(text(x)),actions:['Criar ebook ou guia prático','Gerar checklist/material bônus','Preparar landing page e oferta']},
 {test:x=>/finan|gasto|orçamento|planilha/i.test(text(x)),actions:['Criar planilha ou guia digital','Montar página de demonstração','Preparar oferta de baixo ticket']},
 {test:x=>/whatsapp|atendimento|chatbot|site|lead|agendamento|instagram/i.test(text(x)),actions:['Criar demonstração da solução','Montar proposta comercial','Preparar abordagem para lead com base legítima']},
 {test:()=>true,actions:['Validar problema e público','Criar MVP do produto digital','Preparar página de oferta']}
];
export function buildOpportunityActionPlan(opportunity={}){const rule=actionRules.find(r=>r.test(opportunity));const heat=opportunity.heat||'watch';const priority=heat==='hot'?'agora':heat==='strong'?'alta':heat==='warming'?'média':'observação';const suggestedProduct=productConcept(opportunity);return {opportunityId:opportunity.categoryId||opportunity.id||null,category:opportunity.category||opportunity.title||'Oportunidade',heat,priority,productSuggestion:opportunity.productSuggestion||suggestedProduct.title,suggestedProduct,actions:rule.actions.map((title,index)=>({id:`action-${index+1}`,title,status:'suggested',order:index+1})),autoExecutionAllowed:false,requiresReview:true,reason:'O Radar prepara o plano e a sugestão de produto; publicação, contato com pessoas, alegações sensíveis e gastos exigem revisão/ação autorizada.'}}
export function attachActionPlans(items=[]){return items.map(x=>({...x,actionPlan:buildOpportunityActionPlan(x)}))}
