import {readState,writeState} from './persistence';
const KEY='sales-store';const fallback={events:[],deliveries:[]};
async function getStore(){return readState(KEY,fallback)}
export async function saveSaleEvent(event){const store=await getStore();const i=store.events.findIndex(x=>x.id===event.id);if(i>=0)return {event:store.events[i],duplicate:true};store.events.unshift(event);store.events=store.events.slice(0,500);await writeState(KEY,store);return {event,duplicate:false}}
export async function listSaleEvents(){return (await getStore()).events}
export async function createDelivery({event,asset}){if(!event?.id||!asset)return null;const store=await getStore();const existing=store.deliveries.find(x=>x.eventId===event.id);if(existing)return existing;const now=Date.now();const delivery={id:crypto.randomUUID(),eventId:event.id,buyerEmail:event.buyerEmail||null,asset,status:'ready',token:crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-',''),createdAt:new Date(now).toISOString(),expiresAt:new Date(now+72*60*60*1000).toISOString(),deliveredAt:null,accessCount:0,lastAccessAt:null};store.deliveries.unshift(delivery);store.deliveries=store.deliveries.slice(0,1000);await writeState(KEY,store);return delivery}
export async function getDeliveryByToken(token){return (await getStore()).deliveries.find(x=>x.token===token)||null}
export async function registerDeliveryAccess(token){const store=await getStore();const d=store.deliveries.find(x=>x.token===token);if(!d)return {error:'delivery_not_found'};if(Date.now()>new Date(d.expiresAt).getTime()){d.status='expired';await writeState(KEY,store);return {error:'delivery_expired'}};d.accessCount=(d.accessCount||0)+1;d.lastAccessAt=new Date().toISOString();if(!d.deliveredAt)d.deliveredAt=d.lastAccessAt;d.status='delivered';await writeState(KEY,store);return {delivery:d}}
export async function listDeliveries(){return (await getStore()).deliveries}
