const memory=globalThis.__radarStore||{opportunities:[],searches:[],projects:[],workspaces:{}};
if(!memory.projects)memory.projects=[];if(!memory.workspaces)memory.workspaces={};if(!globalThis.__radarStore)globalThis.__radarStore=memory;
const event=(type,detail={})=>({id:crypto.randomUUID(),type,at:new Date().toISOString(),...detail});
export function saveSearch(search){const record={id:crypto.randomUUID(),createdAt:new Date().toISOString(),...search};memory.searches.unshift(record);memory.searches=memory.searches.slice(0,100);return record}
export function listSearches(){return memory.searches}
export function saveOpportunity(opportunity){const existing=memory.opportunities.findIndex(item=>item.id===opportunity.id);if(existing>=0){const prev=memory.opportunities[existing],timeline=Array.isArray(prev.timeline)?prev.timeline:[];memory.opportunities[existing]={...prev,...opportunity,timeline:[event('seen_again',{label:'Oportunidade encontrada novamente'}),...timeline].slice(0,100)};return memory.opportunities[existing]}const record={...opportunity,timeline:[event('discovered',{label:'Oportunidade descoberta'}),event('saved',{label:'Oportunidade salva'})]};memory.opportunities.unshift(record);return record}
export function listSavedOpportunities(){return memory.opportunities}
export function getSavedOpportunity(id){return memory.opportunities.find(item=>item.id===id)||null}
export function updateOpportunityStatus(id,status){const index=memory.opportunities.findIndex(item=>item.id===id);if(index<0)return null;const prev=memory.opportunities[index],from=prev.status||'new',labels={new:'Restaurada para novo',analyzing:'Análise iniciada',approved:'Oportunidade aprovada',discarded:'Oportunidade descartada'},timeline=Array.isArray(prev.timeline)?prev.timeline:[];memory.opportunities[index]={...prev,status,statusUpdatedAt:new Date().toISOString(),timeline:[event(`status_${status}`,{label:labels[status]||status,from,to:status}),...timeline].slice(0,100)};return memory.opportunities[index]}
export function addOpportunityEvent(id,type,detail={}){const index=memory.opportunities.findIndex(item=>item.id===id);if(index<0)return null;const prev=memory.opportunities[index],timeline=Array.isArray(prev.timeline)?prev.timeline:[];memory.opportunities[index]={...prev,timeline:[event(type,detail),...timeline].slice(0,100)};return memory.opportunities[index]}
export function saveProject(project){const i=memory.projects.findIndex(p=>p.id===project.id);if(i>=0)memory.projects[i]={...memory.projects[i],...project};else memory.projects.unshift(project);return project}
export function listProjects(){return memory.projects}
export function getProject(id){return memory.projects.find(p=>p.id===id)||null}
export function getWorkspace(projectId){return memory.workspaces[projectId]||null}
export function saveWorkspace(workspace){memory.workspaces[workspace.projectId]=workspace;return workspace}
export function updateWorkspaceTask(projectId,taskId,status){const w=memory.workspaces[projectId];if(!w)return null;const task=w.tasks.find(t=>t.id===taskId);if(!task)return null;task.status=status;w.updatedAt=new Date().toISOString();return w}
export function updateProjectRequirements(projectId,requirements={}){const i=memory.projects.findIndex(p=>p.id===projectId);if(i<0)return null;memory.projects[i]={...memory.projects[i],requirements:{...(memory.projects[i].requirements||{}),...requirements},updatedAt:new Date().toISOString()};return memory.projects[i]}
export function addDeployment(projectId,deployment={}){const i=memory.projects.findIndex(p=>p.id===projectId);if(i<0)return null;const history=memory.projects[i].deploymentHistory||[];memory.projects[i]={...memory.projects[i],deployment:{...(memory.projects[i].deployment||{}),...deployment},deploymentHistory:[deployment,...history].slice(0,20),updatedAt:new Date().toISOString()};return memory.projects[i]}
export function saveChannelLifecycle(projectId,channelLifecycle){const i=memory.projects.findIndex(p=>p.id===projectId);if(i<0)return null;memory.projects[i]={...memory.projects[i],channelLifecycle,updatedAt:new Date().toISOString()};return memory.projects[i]}
