const memory=globalThis.__radarStore||{opportunities:[],searches:[],projects:[],workspaces:{}};
if(!memory.projects)memory.projects=[];if(!memory.workspaces)memory.workspaces={};if(!globalThis.__radarStore)globalThis.__radarStore=memory;
const event=(type,detail={})=>({id:crypto.randomUUID(),type,at:new Date().toISOString(),...detail});
const key=v=>String(v||'desconhecido').toLowerCase().trim();
function outcomeOf(o){const t=Array.isArray(o.timeline)?o.timeline:[];const won=t.find(e=>e.type==='sale_won'),lost=t.find(e=>e.type==='sale_lost');if(!won&&!lost)return null;if(won&&lost)return new Date(won.at)>new Date(lost.at)?'won':'lost';return won?'won':'lost'}
function groupStats(selector){const groups={};for(const o of memory.opportunities){const outcome=outcomeOf(o);if(!outcome)continue;const k=key(selector(o));groups[k]||={key:k,wins:0,losses:0,revenue:0,total:0};groups[k].total++;if(outcome==='won'){groups[k].wins++;const win=(o.timeline||[]).find(e=>e.type==='sale_won');groups[k].revenue+=Number(win?.value||0)}else groups[k].losses++}return Object.values(groups).map(g=>({...g,winRate:g.total?Math.round(g.wins/g.total*100):0,confidence:Math.min(100,Math.round(g.total/10*100))})).sort((a,b)=>b.wins-a.wins||b.revenue-a.revenue)}
export function getCommercialLearning(){const closed=memory.opportunities.filter(o=>outcomeOf(o));const wins=closed.filter(o=>outcomeOf(o)==='won');return {sampleSize:closed.length,wins:wins.length,losses:closed.length-wins.length,winRate:closed.length?Math.round(wins.length/closed.length*100):0,revenue:wins.reduce((sum,o)=>{const e=(o.timeline||[]).find(x=>x.type==='sale_won');return sum+Number(e?.value||0)},0),byCategory:groupStats(o=>o.category||o.title),bySource:groupStats(o=>o.source?.name||o.source||'desconhecido'),byScoreBand:groupStats(o=>{const s=Number(o.opportunityScore??o.score??0);return s>=90?'90-100':s>=80?'80-89':s>=70?'70-79':'0-69'})}}
export function getOpportunityLearningAdjustment(o){const learning=getCommercialLearning(),category=learning.byCategory.find(x=>x.key===key(o.category||o.title)),source=learning.bySource.find(x=>x.key===key(o.source?.name||o.source||'desconhecido'));const samples=[category,source].filter(x=>x&&x.total>=2);if(!samples.length)return {adjustment:0,confidence:0,reason:'Histórico comercial insuficiente'};const weighted=samples.reduce((sum,x)=>sum+(x.winRate-50)*(x.confidence/100),0)/samples.length;const adjustment=Math.max(-10,Math.min(10,Math.round(weighted/5)));const confidence=Math.round(samples.reduce((s,x)=>s+x.confidence,0)/samples.length);return {adjustment,confidence,reason:`Baseado em ${samples.reduce((s,x)=>s+x.total,0)} resultados semelhantes`}}
export function saveSearch(search){const record={id:crypto.randomUUID(),createdAt:new Date().toISOString(),...search};memory.searches.unshift(record);memory.searches=memory.searches.slice(0,100);return record}
export function listSearches(){return memory.searches}
export function saveOpportunity(opportunity){const existing=memory.opportunities.findIndex(item=>item.id===opportunity.id);if(existing>=0){const prev=memory.opportunities[existing],timeline=Array.isArray(prev.timeline)?prev.timeline:[];memory.opportunities[existing]={...prev,...opportunity,timeline:[event('seen_again',{label:'Oportunidade encontrada novamente'}),...timeline].slice(0,100)};return memory.opportunities[existing]}const record={...opportunity,timeline:[event('discovered',{label:'Oportunidade descoberta'}),event('saved',{label:'Oportunidade salva'})]};memory.opportunities.unshift(record);return record}
export function listSavedOpportunities(){return memory.opportunities}
export function getSavedOpportunity(id){return memory.opportunities.find(item=>item.id===id)||null}
export function updateOpportunityStatus(id,status){const index=memory.opportunities.findIndex(item=>item.id===id);if(index<0)return null;const prev=memory.opportunities[index],from=prev.status||'new',labels={new:'Restaurada para novo',analyzing:'Análise iniciada',approved:'Oportunidade aprovada',discarded:'Oportunidade descartada'},timeline=Array.isArray(prev.timeline)?prev.timeline:[];memory.opportunities[index]={...prev,status,statusUpdatedAt:new Date().toISOString(),timeline:[event(`status_${status}`,{label:labels[status]||status,from,to:status}),...timeline].slice(0,100)};return memory.opportunities[index]}
export function addOpportunityEvent(id,type,detail={}){const index=memory.opportunities.findIndex(item=>item.id===id);if(index<0)return null;const prev=memory.opportunities[index],timeline=Array.isArray(prev.timeline)?prev.timeline:[];memory.opportunities[index]={...prev,timeline:[event(type,detail),...timeline].slice(0,100)};return memory.opportunities[index]}
export function saveProject(project){const i=memory.projects.findIndex(p=>p.id===project.id);if(i>=0)memory.projects[i]={...memory.projects[i],...project};else memory.projects.unshift(project);return project}
export function listProjects(){return memory.projects}
export function getProject(id){return memory.projects.find(p=>p.id===id)||null}
export function getWorkspace(projectId){return memory.workspaces[projectId]||null}
export function saveWorkspace(workspace){memory.workspaces[workspace.projectId]=workspace;return workspace}
export function updateWorkspaceTask(projectId,taskId,status){const w=memory.workspaces[projectId];if(!w)return null;const task=w.tasks.find(t=>t.id===taskId);if(!task)return null;task.status=status;w.updatedAt=new Date().toISOString();return w}
export function updateProjectRequirements(projectId,requirements={}){const i=memory.projects.findIndex(p=>p.id===projectId);if(i<0)return null;memory.projects[i]={...memory.projects[i],requirements:{...(memory.projects[i].requirements||{}),...requirements},updatedAt:new Date().toISOString()};return memory.projects[i]}
export function addDeployment(projectId,deployment={}){const i=memory.projects.findIndex(p=>p.id===projectId);if(i<0)return null;const history=memory.projects[i].deploymentHistory||[];memory.projects[i]={...memory.projects[i],deployment:{...(memory.projects[i].deployment||{}),...deployment},deploymentHistory:[deployment,...history].slice(0,20),updatedAt:new Date().toISOString()};return memory.projects[i]}
export function saveChannelLifecycle(projectId,channelLifecycle){const i=memory.projects.findIndex(p=>p.id===projectId);if(i<0)return null;memory.projects[i]={...memory.projects[i],channelLifecycle,updatedAt:new Date().toISOString()};return memory.projects[i]}
