'use client';
import {useEffect,useState} from 'react';
export default function OpportunityPage(){
 const[o,setO]=useState(null);const[solutions,setSolutions]=useState([]);const[chosen,setChosen]=useState(null);const[draft,setDraft]=useState(null);const[apollo,setApollo]=useState(null);const[candidates,setCandidates]=useState([]);const[selected,setSelected]=useState(null);const[busy,setBusy]=useState(false);const[searching,setSearching]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{try{const raw=sessionStorage.getItem('radar:selected');if(raw){const item=JSON.parse(raw);setO(item);fetch('/api/solution-match',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(item)}).then(r=>r.json()).then(p=>setSolutions(p.data||[]))}}catch{}},[]);
 async function prepare(){if(!o)return;const r=await fetch('/api/outreach-draft',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...o,solution:chosen})});setDraft((await r.json()).data)}
 async function prepareApollo(){if(!o)return;setBusy(true);setError('');try{const r=await fetch('/api/apollo-plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(o)});setApollo((await r.json()).data)}finally{setBusy(false)}}
 async function searchCandidates(){if(!apollo?.domain)return;setSearching(true);setError('');setCandidates([]);setSelected(null);try{const r=await fetch('/api/apollo-search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({domain:apollo.domain})});const p=await r.json();if(!r.ok)throw new Error(p.error||'Falha na busca');setCandidates(p.data||[]);if(p.meta?.configured===false)setError('Apollo ainda não está configurado no servidor.')}catch(e){setError(e.message)}finally{setSearching(false)}}
 if(!o)return <main className="detail"><a href="/">← Voltar</a><div className="panel"><h1>Nenhuma oportunidade selecionada</h1></div></main>;
 return <main className="detail"><a href="/">← Voltar ao Radar</a><div className="detailGrid"><section className="panel"><small>OPORTUNIDADE</small><h1>{o.title}</h1><div className="detailScore">Score {o.score} · {o.intent} intenção</div><h3>Evidência</h3><p>{o.evidence||o.problem||'Sem trecho adicional.'}</p>{o.source?.url&&<a className="linkBtn" href={o.source.url} target="_blank" rel="noreferrer">Abrir fonte original ↗</a>}</section><aside className="panel"><h2>Próxima ação</h2><p>Status: <strong>{o.status||'new'}</strong></p><p>Solução escolhida: <strong>{chosen?.name||'A escolher'}</strong></p><button onClick={prepareApollo} disabled={busy}>{busy?'Verificando...':'Preparar busca no Apollo'}</button><button className="open" onClick={prepare}>Preparar abordagem</button></aside></div><section className="panel draft"><small>FÁBRICA DE SOLUÇÕES</small><h2>O que podemos oferecer</h2>{solutions.length?<div className="candidateGrid">{solutions.map(s=><article className={'candidate '+(chosen?.id===s.id?'selected':'')} key={s.id}><h3>{s.name}</h3><p>Compatibilidade: {s.matchScore}%</p><small>Demo: {s.demo}</small><p>{s.deliverables.join(' · ')}</p><button className="open" onClick={()=>setChosen(s)}>{chosen?.id===s.id?'Solução escolhida':'Escolher solução'}</button></article>)}</div>:<p>Nenhuma solução pronta correspondeu claramente. Não oferecer automaticamente até revisar a necessidade.</p>}</section>{apollo&&<section className="panel draft"><small>APOLLO</small><h2>Decisores profissionais</h2><p>Domínio: <strong>{apollo.domain||'não identificado'}</strong></p>{apollo.canSearch?<button onClick={searchCandidates} disabled={searching||!apollo.domain}>{searching?'Procurando...':'Buscar candidatos no Apollo'}</button>:<p>Ainda precisamos identificar a empresa ou domínio correto.</p>}{error&&<p className="apolloError">{error}</p>}{candidates.length>0&&<div className="candidateGrid">{candidates.map(c=><article className={'candidate '+(selected?.id===c.id?'selected':'')} key={c.id}><h3>{c.name||'Nome protegido'}</h3><p>{c.title||'Cargo não informado'}</p><small>{c.organization||apollo.company||apollo.domain}</small>{c.linkedinUrl&&<a href={c.linkedinUrl} target="_blank" rel="noreferrer">LinkedIn ↗</a>}<button className="open" onClick={()=>setSelected(c)}>{selected?.id===c.id?'Selecionado':'Selecionar'}</button></article>)}</div>}</section>}{draft&&<section className="panel draft"><h2>Rascunho para revisão</h2><h3>{draft.draft.subject}</h3><p>{draft.draft.message}</p><small>Não enviado automaticamente. Revise antes de qualquer contato.</small></section>}</main>
}
