import {NextResponse} from 'next/server';
import {analyzePublicDemand} from '../../../lib/digital-demand';
import {rankDemandSignals} from '../../../lib/demand-ranking';
import {saveDemandSnapshot,getDemandTrends} from '../../../lib/demand-history';
import {prioritizeHotOpportunities} from '../../../lib/hot-opportunity';
import {listExecutionEvents} from '../../../lib/execution-history';
function clamp(n,min=0,max=100){return Math.max(min,Math.min(max,n))}
function norm(v=''){return String(v).trim().toLowerCase()}
function buildLearning(events=[]){const map=new Map();for(const e of events){if(!e.category)continue;const key=norm(e.category);const g=map.get(key)||{samples:0,sales:0,revenue:0,products:0,completed:0,refunds:0};g.samples++;if(e.type==='sale'){g.sales++;g.revenue+=Math.max(0,Number(e.value||0))}if(e.type==='refund')g.refunds++;if(e.type==='product_created')g.products++;if(e.type==='opportunity_completed')g.completed++;map.set(key,g)}return map}
function learnedBoost(category,learning){const g=learning.get(norm(category));if(!g)return {boost:0,confidence:0,samples:0};const confidence=Math.min(1,g.samples/20);const raw=Math.min(15,g.sales*4+g.products*1.5+g.completed*.75+Math.min(g.revenue/200,6)-g.refunds*3);return {boost:Math.round(raw*confidence*10)/10,confidence:Math.round(confidence*100),samples:g.samples,stats:g}}
function explain(x,learned,trend){const reasons=[];reasons.push({factor:'score_base',label:'Força dos sinais atuais',value:Number(x.opportunityScore||0),detail:'Score calculado antes do aprendizado histórico.'});if(Number(x.intentScore||0)>0)reasons.push({factor:'intent',label:'Intenção observada',value:Number(x.intentScore),detail:'Há sinais públicos/agrupados classificados como intenção.'});if(Number(x.volume||0)>0)reasons.push({factor:'volume',label:'Volume de sinais',value:Number(x.volume),detail:'Quantidade de sinais elegíveis associados à demanda.'});if(Number(x.sourceDiversity||0)>0)reasons.push({factor:'sources',label:'Diversidade de fontes',value:Number(x.sourceDiversity),detail:'Mais de uma origem reduz dependência de um único sinal.'});if(trend)reasons.push({factor:'trend',label:'Tendência histórica',value:trend.direction||trend.trend||'observada',detail:'Comparação com snapshots anteriores disponíveis no Radar.'});if(learned.samples>0)reasons.push({factor:'learning',label:'Histórico comercial',value:`+${learned.boost} pontos`,detail:`${learned.samples} evento(s), confiança ${learned.confidence}%. O bônus é limitado para evitar excesso de peso com poucos dados.`});else reasons.push({factor:'learning',label:'Histórico comercial',value:'sem bônus',detail:'Ainda não existe histórico suficiente desta categoria; ela não é penalizada por isso.'});return reasons}
export async function POST(request){const body=await request.json();const items=Array.isArray(body.items)?body.items:[];const allowed=items.filter(x=>['public','aggregate','public_or_aggregate'].includes(x.signalType||'public_or_aggregate'));const signals=analyzePublicDemand(allowed);const ranking=rankDemandSignals(signals);const snapshotAt=ranking.length?await saveDemandSnapshot(ranking):null;const[trends,events]=await Promise.all([getDemandTrends(),listExecutionEvents()]);const trendMap=new Map(trends.map(x=>[x.categoryId,x])),learning=buildLearning(events);const enriched=ranking.map(x=>{const learned=learnedBoost(x.category,learning),trend=trendMap.get(x.categoryId)||null,finalScore=clamp(Math.round((x.opportunityScore+learned.boost)*10)/10);return {...x,baseOpportunityScore:x.opportunityScore,opportunityScore:finalScore,trend,learning:{boost:learned.boost,confidence:learned.confidence,samples:learned.samples,stats:learned.stats||null},recommendation:{recommended:finalScore>=70,summary:finalScore>=85?'Prioridade alta: sinais atuais fortes e/ou histórico favorável.':finalScore>=70?'Oportunidade relevante: vale analisar antes de produzir.':'Ainda não há evidência suficiente para prioridade.',reasons:explain(x,learned,trend),caution:learned.confidence<50?'Histórico ainda possui confiança limitada; dê mais peso aos sinais atuais.':null}}});const prioritized=prioritizeHotOpportunities(enriched);return NextResponse.json({data:prioritized,meta:{received:items.length,eligible:allowed.length,matched:signals.length,snapshotAt,hot:prioritized.filter(x=>x.heat==='hot').length,learning:'Histórico real pode adicionar no máximo 15 pontos, reduzidos pela confiança amostral. Categorias sem histórico não recebem bônus.',explainability:'Cada oportunidade inclui recommendation com resumo, fatores observados e alerta de confiança.',privacy:'Somente sinais públicos ou agregados são aceitos para ranking.'}})}
