import {NextResponse} from 'next/server';
import {analyzePublicDemand} from '../../../lib/digital-demand';
import {rankDemandSignals} from '../../../lib/demand-ranking';
import {saveDemandSnapshot,getDemandTrends} from '../../../lib/demand-history';
import {prioritizeHotOpportunities} from '../../../lib/hot-opportunity';
import {listExecutionEvents} from '../../../lib/execution-history';
function clamp(n,min=0,max=100){return Math.max(min,Math.min(max,n))}
function norm(v=''){return String(v).trim().toLowerCase()}
function buildLearning(events=[]){const map=new Map();for(const e of events){if(!e.category)continue;const key=norm(e.category);const g=map.get(key)||{samples:0,sales:0,revenue:0,products:0,completed:0,refunds:0};g.samples++;if(e.type==='sale'){g.sales++;g.revenue+=Math.max(0,Number(e.value||0))}if(e.type==='refund')g.refunds++;if(e.type==='product_created')g.products++;if(e.type==='opportunity_completed')g.completed++;map.set(key,g)}return map}
function learnedBoost(category,learning){const g=learning.get(norm(category));if(!g)return {boost:0,confidence:0,samples:0};const confidence=Math.min(1,g.samples/20);const raw=Math.min(15,g.sales*4+g.products*1.5+g.completed*.75+Math.min(g.revenue/200,6)-g.refunds*3);return {boost:Math.round(raw*confidence*10)/10,confidence:Math.round(confidence*100),samples:g.samples,stats:g}}
export async function POST(request){const body=await request.json();const items=Array.isArray(body.items)?body.items:[];const allowed=items.filter(x=>['public','aggregate','public_or_aggregate'].includes(x.signalType||'public_or_aggregate'));const signals=analyzePublicDemand(allowed);const ranking=rankDemandSignals(signals);const snapshotAt=ranking.length?await saveDemandSnapshot(ranking):null;const[trends,events]=await Promise.all([getDemandTrends(),listExecutionEvents()]);const trendMap=new Map(trends.map(x=>[x.categoryId,x])),learning=buildLearning(events);const enriched=ranking.map(x=>{const learned=learnedBoost(x.category,learning);return {...x,baseOpportunityScore:x.opportunityScore,opportunityScore:clamp(Math.round((x.opportunityScore+learned.boost)*10)/10),trend:trendMap.get(x.categoryId)||null,learning:{boost:learned.boost,confidence:learned.confidence,samples:learned.samples,stats:learned.stats||null}}});const prioritized=prioritizeHotOpportunities(enriched);return NextResponse.json({data:prioritized,meta:{received:items.length,eligible:allowed.length,matched:signals.length,snapshotAt,hot:prioritized.filter(x=>x.heat==='hot').length,learning:'Histórico real pode adicionar no máximo 15 pontos, reduzidos pela confiança amostral. Categorias sem histórico não recebem bônus.',privacy:'Somente sinais públicos ou agregados são aceitos para ranking.'}})}
